lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: Dario Sanfilippo

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://dariosanfilippo.com"
    - Learn markdown: "https:dariosanfilippo.com/"
  Author's home: "https://dariosanfilippo.com"

theme: jekyll-theme-minimal

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  #- CONTRIBUTING.md
  - README.md
    #- LICENSE.md
    #- COPYING.md
    #- CODE_OF_CONDUCT.md
    #- CONTRIBUTING.md
    #- ISSUE_TEMPLATE.md
    #- PULL_REQUEST_TEMPLATE.md
