lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: Dario Sanfilippo

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://dariosanfilippo.com"
    - Learn markdown: "https:dariosanfilippo.com/"
  Author's home: "https://dariosanfilippo.com"
