lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: Dario Sanfilippo

header_pages:
  About: "about"

navbar-links:
  About Me: "ABOUT.md"
  Resources:
    - Beautiful Jekyll: "https://dariosanfilippo.com"
    - Learn markdown: "https:dariosanfilippo.com/"
  Author's home: "https://dariosanfilippo.com"
  #
  #    #theme: jekyll-theme-minimal
  #
  #plugins:
  #  - jekyll-relative-links
  #relative_links:
  #  enabled: true
  #  collections: true
  #include:
  #  - README.md
  #  - ABOUT.md
